apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-run-a-1
  labels:
    pipeline: pipeline-a
spec:
  pipelineRef:
    name: pipeline-a
  trigger:
    type: manual
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-run-a-2
  labels:
    pipeline: pipeline-a
spec:
  pipelineRef:
    name: pipeline-a
  trigger:
    type: manual
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-run-b-1
  labels:
    pipeline: pipeline-b
spec:
  pipelineRef:
    name: pipeline-b
  trigger:
    type: manual
