apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-1
spec:
  steps:
    - name: task-1
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-2
spec:
  steps:
    - name: task-2
      image: ubuntu
      command:
        - echo
      args:
        - "hello world2"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-3
spec:
  steps:
    - name: task-3
      image: ubuntu
      command:
        - echo
      args:
        - "hello world 3"